### ISSUE TITLE
HeartBeat  Error

### ISSUE THREAD

**Issue by randy-johnson** [transistorsoft/nativescript-background-geolocation-lt#74] opened 2017-05-05 01:21 UTC
## Your Environment
Plugin version: 1.4
Platform: Android
OS version: 7
Device manufacturer / model: Nexus 6P
Nativescript version (tns info): 2.5.3

desiredAccuracy: 0,
distanceFilter: 50,
heartbeatInterval: 15,
autoSync: true,
startOnBoot:true
url
params
method:"post"

When my heartbeat interval is running I am getting errors in the log file and the getCurrentPosition does not run.

Here is the heartbeat interval function:
```
bgGeo.BackgroundGeolocation.on('heartbeat', function(params) {
  console.log('- hearbeat:'+new Date());
  //alert('- hearbeat:'+new Date());
  // You could request a new location if you wish.
  
  bgGeo.BackgroundGeolocation.getCurrentPosition(function(location, taskId) {
    console.log('- current location: ', location);
    bgGeo.BackgroundGeolocation.finish(taskId);
  });
});     
```

I see the console.log when the function kicks on.

Here is the log cat errors:

```
05-04 21:07:22.283 11945 11945 V JS      : - hearbeat:Thu May 04 2017 21:07:22 GMT-0400 (EDT)
05-04 21:07:22.295 11945 11945 E EventBus: Could not dispatch event: class com.transistorsoft.locationmanager.event.HeartbeatEvent to subscribing class class com.transistorsoft.locationmanager.adapter.BackgroundGeolocation
05-04 21:07:22.295 11945 11945 E EventBus: com.tns.NativeScriptException:
05-04 21:07:22.295 11945 11945 E EventBus: Calling js method success failed
05-04 21:07:22.295 11945 11945 E EventBus:
05-04 21:07:22.295 11945 11945 E EventBus: Error: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
05-04 21:07:22.295 11945 11945 E EventBus:     org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
05-04 21:07:22.295 11945 11945 E EventBus:     org.json.JSONTokener.nextValue(JSONTokener.java:94)
05-04 21:07:22.295 11945 11945 E EventBus:     org.json.JSONObject.<init>(JSONObject.java:156)
05-04 21:07:22.295 11945 11945 E EventBus:     org.json.JSONObject.<init>(JSONObject.java:173)
05-04 21:07:22.295 11945 11945 E EventBus:     com.tns.Runtime.callJSMethodNative(Native Method)
05-04 21:07:22.295 11945 11945 E EventBus:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
05-04 21:07:22.295 11945 11945 E EventBus:     com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
05-04 21:07:22.295 11945 11945 E EventBus:     com.tns.Runtime.callJSMethod(Runtime.java:890)
05-04 21:07:22.295 11945 11945 E EventBus:     com.tns.Runtime.callJSMethod(Runtime.java:874)
05-04 21:07:22.295 11945 11945 E EventBus:     com.tns.Runtime.callJSMethod(Runtime.java:866)
05-04 21:07:22.295 11945 11945 E EventBus:     com.tns.gen.com.transistorsoft.locationmanager.adapter.TSCallback.success(com.transistorsoft.locationmanager.adapter.TSCallback.java)
05-04 21:07:22.295 11945 11945 E EventBus:     com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.onHeartbeat(Unknown Source)
05-04 21:07:22.295 11945 11945 E EventBus:     java.lang.reflect.Method.invoke(Native Method)
05-04 21:07:22.295 11945 11945 E EventBus:     org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
05-04 21:07:22.295 11945 11945 E EventBus:     org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
05-04 21:07:22.295 11945 11945 E EventBus:     org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
05-04 21:07:22.295 11945 11945 E EventBus:     android.os.Handler.dispatchMessage(Handler.java:102)
05-04 21:07:22.295 11945 11945 E EventBus:     android.os.Looper.loop(Looper.java:154)
05-04 21:07:22.295 11945 11945 E EventBus:     android.app.ActivityThread.main(ActivityThread.java:6077)
05-04 21:07:22.295 11945 11945 E EventBus:     java.lang.reflect.Method.invoke(Native Method)
05-04 21:07:22.295 11945 11945 E EventBus:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
05-04 21:07:22.295 11945 11945 E EventBus:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
05-04 21:07:22.295 11945 11945 E EventBus: File: "file:///data/data/myapp/files/app/tns_modules/nativescript-background-geolocation-lt/background-geolocation.js, line: 157, column: 45
05-04 21:07:22.295 11945 11945 E EventBus:
05-04 21:07:22.295 11945 11945 E EventBus: StackTrace:
05-04 21:07:22.295 11945 11945 E EventBus:      Frame: function:'BackgroundGeolocation.getCurrentPosition', file:'file:///data/data/myapp/files/app/tns_modules/nativescript-background-geolocation-lt/background-geolocation.js', line: 157, column: 46
05-04 21:07:22.295 11945 11945 E EventBus:      Frame: function:'', file:'file:///data/data/myapp/files/app/views/offers/offers.js', line: 167, column: 31
05-04 21:07:22.295 11945 11945 E EventBus:      Frame: function:'success', file:'file:///data/data/myapp/files/app/tns_modules/nativescript-background-geolocation-lt/background-geolocation.js', line: 50, column: 25
05-04 21:07:22.295 11945 11945 E EventBus:
05-04 21:07:22.295 11945 11945 E EventBus:
05-04 21:07:22.295 11945 11945 E EventBus:      at com.tns.Runtime.callJSMethodNative(Native Method)
05-04 21:07:22.295 11945 11945 E EventBus:      at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
05-04 21:07:22.295 11945 11945 E EventBus:      at com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
05-04 21:07:22.295 11945 11945 E EventBus:      at com.tns.Runtime.callJSMethod(Runtime.java:890)
05-04 21:07:22.295 11945 11945 E EventBus:      at com.tns.Runtime.callJSMethod(Runtime.java:874)
05-04 21:07:22.295 11945 11945 E EventBus:      at com.tns.Runtime.callJSMethod(Runtime.java:866)
05-04 21:07:22.295 11945 11945 E EventBus:      at com.tns.gen.com.transistorsoft.locationmanager.adapter.TSCallback.success(com.transistorsoft.locationmanager.adapter.TSCallback.java)
05-04 21:07:22.295 11945 11945 E EventBus:      at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.onHeartbeat(Unknown Source)
05-04 21:07:22.295 11945 11945 E EventBus:      at java.lang.reflect.Method.invoke(Native Method)
05-04 21:07:22.295 11945 11945 E EventBus:      at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
05-04 21:07:22.295 11945 11945 E EventBus:      at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
05-04 21:07:22.295 11945 11945 E EventBus:      at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
05-04 21:07:22.295 11945 11945 E EventBus:      at android.os.Handler.dispatchMessage(Handler.java:102)
05-04 21:07:22.295 11945 11945 E EventBus:      at android.os.Looper.loop(Looper.java:154)
05-04 21:07:22.295 11945 11945 E EventBus:      at android.app.ActivityThread.main(ActivityThread.java:6077)
05-04 21:07:22.295 11945 11945 E EventBus:      at java.lang.reflect.Method.invoke(Native Method)
05-04 21:07:22.295 11945 11945 E EventBus:      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
05-04 21:07:22.295 11945 11945 E EventBus:      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
05-04 21:07:22.295 11945 11945 E EventBus: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
05-04 21:07:22.295 11945 11945 E EventBus:      at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
05-04 21:07:22.295 11945 11945 E EventBus:      at org.json.JSONTokener.nextValue(JSONTokener.java:94)
05-04 21:07:22.295 11945 11945 E EventBus:      at org.json.JSONObject.<init>(JSONObject.java:156)
05-04 21:07:22.295 11945 11945 E EventBus:      at org.json.JSONObject.<init>(JSONObject.java:173)
05-04 21:07:22.295 11945 11945 E EventBus:      ... 18 more
```

**Comment by randy-johnson** [comment] 2017-05-05 01:54
I found another example in the docs:

`
bgGeo.BackgroundGeolocation.getCurrentPosition(function(location, taskId) {
  // This location is already persisted to plugin’s SQLite db.  
  // If you’ve configured #autoSync: true, the HTTP POST has already started.
  console.log("- Current position received: ", location);
  console.dump(location);
  bgGeo.BackgroundGeolocation.finish(taskId);
}, function(errorCode) {
  alert('An location error occurred: ' + errorCode);
}, {
  timeout: 30,      // 30 second timeout to fetch location
  maximumAge: 5000, // Accept the last-known-location if not older than 5000 ms.
  desiredAccuracy: 10,  // Try to fetch a location with an accuracy of `10` meters.
  samples: 3,   // How many location samples to attempt.
  extras: {         // [Optional] Attach your own custom `metaData` to this location.  This metaData will be persisted to SQLite and POSTed to your server
    foo: "bar"  
  }
});
`

That doesn't throw the error in the log file but isn't doing an http post as it says in the above code example:

// If you’ve configured #autoSync: true, the HTTP POST has already started.

It is sending the data to the console but the http isn't seem to be happening.

**Comment by christocracy** [comment] 2017-05-05 13:49
To syntax highlight *code-blocks*, use 3-backticks.  Read the [Markdown docs](https://guides.github.com/features/mastering-markdown/)

**Comment by christocracy** [comment] 2017-05-05 14:02
When I do a `getCurrentPosition` in the demo app, I see in the logs:
```
05-05 10:00:56.466  8299  8504 D TSLocationManager: [c.t.l.LocationService onLocation]
05-05 10:00:56.466  8299  8504 D TSLocationManager: ╔═════════════════════════════════════════════
05-05 10:00:56.466  8299  8504 D TSLocationManager: ║ LocationService: location:1003
05-05 10:00:56.466  8299  8504 D TSLocationManager: ╠═════════════════════════════════════════════
05-05 10:00:56.466  8299  8504 D TSLocationManager: ╟─ 📍  Location[fused 45.519280,-73.617008 acc=20 et=+14d16h35m31s340ms]
05-05 10:00:56.494  8299  8504 I TSLocationManager: [c.t.l.l.TSLocationManager onSingleLocationResult]
05-05 10:00:56.494  8299  8504 I TSLocationManager:   🔵  Acquired current position
05-05 10:00:56.507  8299  8504 D TSLocationManager: [c.t.l.l.TSLocationManager calculateMedianAccuracy] 19.532
05-05 10:00:56.563  8299  8500 I TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO persist]
05-05 10:00:56.563  8299  8500 I TSLocationManager:   ✅  INSERT: 60727641-7533-4ecd-a545-d2cdaf12034b
05-05 10:00:56.587  8299  8500 D TSLocationManager: [c.t.l.http.HttpService flush]
05-05 10:00:56.587  8299  8500 D TSLocationManager: ╔═════════════════════════════════════════════
05-05 10:00:56.587  8299  8500 D TSLocationManager: ║ HTTP Service
05-05 10:00:56.587  8299  8500 D TSLocationManager: ╠═════════════════════════════════════════════
05-05 10:00:56.591  8299  8504 D TSLocationManager: [c.t.l.LocationService onHeartbeat] ❤️
05-05 10:00:56.605  8299  8500 D TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO first]
05-05 10:00:56.605  8299  8500 D TSLocationManager:   ✅  Locked 1 records
05-05 10:00:56.618  8299  8299 I TSLocationManager: [c.t.l.http.HttpService flush]
05-05 10:00:56.618  8299  8299 I TSLocationManager:   ℹ️  HttpService is busy
05-05 10:00:56.618  8299  8500 I TSLocationManager: [c.t.l.http.HttpService createRequest]
05-05 10:00:56.618  8299  8500 I TSLocationManager:   🔵  POST: 60727641-7533-4ecd-a545-d2cdaf12034b
05-05 10:00:56.664  8299  8371 I TSLocationManager: [c.t.l.http.HttpRequest parseNetworkResponse]
05-05 10:00:56.664  8299  8371 I TSLocationManager:   🔵  Response: 200
05-05 10:00:56.676  8299  8299 D TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO destroy]
05-05 10:00:56.676  8299  8299 D TSLocationManager:   ✅  DESTROY: 60727641-7533-4ecd-a545-d2cdaf12034b
```

Watch the Android logs with `$ adb logcat -s TSLocationManager`

**Comment by christocracy** [comment] 2017-05-05 14:13
The problem is a bug in the plugin's Javascript for `getCurrentPosition`, where it's failing to create a default `options {}` when none is provided.

In the meantime, simply provide an `error` callback and empty options `{}`

```
BackgroundGeolocation.getCurrentPosition(successFn, errorFn, {});
```

**Comment by christocracy** [comment] 2017-05-05 14:15
Fixed in master.

**Closed by christocracy** 2017-05-05 14:15 UTC
Labels: bug
